name: Keep Backend Alive

# Run every 10 minutes to keep Render backend awake
on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:  # Allow manual runs

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: |
          echo "Pinging backend..."
          curl -f "https://saco-ai-assistant.onrender.com/ping" || exit 1
          echo "✅ Backend is alive!"
